### ISSUE TITLE
RFE: Member management with Peribolos

### ISSUE THREAD

**Issue by aepfli** [keptn/community#220]
### Proposal

Within #174 we're already discussing the adaption of Peribolos, which makes managing memberships and repository assignments easier.

Peribolos itself offers a great variety of settings and can be used to manage not only organization management but also team assignments and repository permissions.

#### What do we want?

1. We want to have a GitOps way of assigning different permissions to members of our organization.
1. We want to have an easy approach with little to no duplication or too many points to edit alignment
1. We want to organize our members in teams with certain aspects.
1. We don't want to assign permissions per individual but on a team basis, so if you want specific permissions, you're part of a certain team.
1. We want to group repositories for teams, aka one team is responsible for multiple repositories - to reduce maintenance efforts
1. We also want to have overlapping teams for repositories as their might be the need to separate some access

##### Organization Level

First we do have roles on organizational level like:

    Owners
    Members

With respective permissions

##### Repository Level

Additionally if you are part of the organizational level you can also be one of those roles just for repository or repository group:

    Repo-Maintainer
    Repo-Approver

#### Proposal

In the end we can setup the repo-permissions for each repository, which means currently we would have 24 x 3 groups per github.com/keptn alone (if we need a dedicated group for all of them) but grouping would be easier and way better to handle.

<details>
  <summary>Theoretically we could group the repository as follow (naive proposal)</summary>

 * klt:
     * lifecycle-toolkit
     * wg-app-lifecycle
 * ops: (operational topics regarding how we deliver keptn)
     * helm-charts
     * helm-charts-dev
     * get.keptn.sh
     * gh-automation
     * dns.keptn.sh
 * keptn:
     * go-utils
     * keptn
     * examples
     * spec
     * integrations
     * kubernetes-utils
 * docs:
     * keptn.github.io
tutorials
 * org:
   * enhancement-proposals
   * community
   * .github
   * toc
 * utils:
     * gh-action-extract-branch-name
     * keptn-on-keptn (not sure about that one)
     * gh-action-send-event
     * gh-action-build-docker-image
     * gh-action-ci-prepare-keptn-cluster
</details>

As the configuration file for this structure would be already quiet big and cover a lot of duplication

<details>
  <summary>one config file for proposed solution without members</summary>

   ```yaml
orgs:
  keptn:
    # org settings
    company: foo
    email: foo
    name: foo
    description: foo
    has_organization_projects: true
    has_repository_projects: true
    default_repository_permission: read
    members_can_create_repositories: false

    # org member settings
    members:
    - anne
    - bob
    admins:
    - carl

    # team settings
    teams:
      # Parent group for all maintainers so we do have an overview over all maintainers
      maintainers: 
        # team config
        description: Keptn Maintainers
        privacy: closed

        repos:
          lifecycle-toolkit: maintain
          wg-app-lifecycle: maintain

          helm-charts: maintain
          helm-charts-dev: maintain
          get.keptn.sh: maintain
          gh-automation: maintain
          dns.keptn.sh: maintain

          go-utils: maintain
          keptn: maintain
          examples: maintain
          spec: maintain
          integrations: maintain
          kubernetes-utils: maintain

          keptn.github.io: maintain
          tutorials: maintain

          enhancement-proposals: maintain
          community: maintain
          .github: maintain
          toc: maintain

          gh-action-extract-branch-name: maintain
          keptn-on-keptn: maintain
          gh-action-send-event: maintain
          gh-action-build-docker-image: maintain
          gh-action-ci-prepare-keptn-cluster: maintain
      
      # Parent group for all approvers so we do have an overview over all approvers
      approvers:
        # team config
        description: Keptn Approvers
        privacy: closed
        repos:
          lifecycle-toolkit: triage
          wg-app-lifecycle: triage

          helm-charts: triage
          helm-charts-dev: triage
          get.keptn.sh: triage
          gh-automation: triage
          dns.keptn.sh: triage

          go-utils: triage
          keptn: triage
          examples: triage
          spec: triage
          integrations: triage
          kubernetes-utils: triage

          keptn.github.io: triage
          tutorials: triage

          enhancement-proposals: triage
          community: triage
          .github: triage
          toc: triage

          gh-action-extract-branch-name: triage
          keptn-on-keptn: triage
          gh-action-send-event: triage
          gh-action-build-docker-image: triage
          gh-action-ci-prepare-keptn-cluster: triage
      
      klt-approver:
        children: klt-maintainers
        repos:
          lifecycle-toolkit: triage
          wg-app-lifecycle: triage
      klt-maintainers:
        repos:
          lifecycle-toolkit: maintain
          wg-app-lifecycle: maintain
      ops-approver:
        children: ops-maintainers
        repos:
          helm-charts: triage
          helm-charts-dev: triage
          get.keptn.sh: triage
          gh-automation: triage
          dns.keptn.sh: triage
      ops-maintainers:
        repos:
          helm-charts: maintain
          helm-charts-dev: maintain
          get.keptn.sh: maintain
          gh-automation: maintain
          dns.keptn.sh: maintain
      keptn-approver:
        children: keptn-maintainers
        repos:
          go-utils: triage
          keptn: triage
          examples: triage
          spec: triage
          integrations: triage
          kubernetes-utils: triage
      keptn-maintainers:
        repos:
          go-utils: maintain
          keptn: maintain
          examples: maintain
          spec: maintain
          integrations: maintain
          kubernetes-utils: maintain
      docs-approver:
        children: docs-maintainers
        repos:
          keptn.github.io: triage
          tutorials: triage
      docs-maintainers:
        repos:
          keptn.github.io: maintain
          tutorials: maintain
      org-approvers:
        children: org-maintainers
        repos:
          enhancement-proposals: triage
          community: triage
          .github: triage
          toc: triage
      org-maintainers:
        repos:
          enhancement-proposals: maintain
          community: maintain
          .github: maintain
          toc: maintain
      utils-approvers:
        children: utils-maintainers
        repos:
          gh-action-extract-branch-name: triage
          keptn-on-keptn: triage
          gh-action-send-event: triage
          gh-action-build-docker-image: triage
          gh-action-ci-prepare-keptn-cluster: triage
      utils-maintainers:
        repos:
          gh-action-extract-branch-name: maintain
          keptn-on-keptn: maintain
          gh-action-send-event: maintain
          gh-action-build-docker-image: maintain
          gh-action-ci-prepare-keptn-cluster: maintain
   ```
</details>

I propose consolidating this into a leaner structure with an automatic merge (like Kubernetes is doing https://github.com/kubernetes/org) tailored to our needs. We will have an own Directory per organization we manage, either a subdirectory per group or a yaml file per group which will contain the necessary information see:
![image](https://user-images.githubusercontent.com/9987394/217242924-572dc9a1-bec8-4e75-8d58-c35226f77a14.png)

The `org.yaml` will contain basic information about the organization, such as general membership, description, etc.
The group configuration (either within a subfolder, or directly named) will contain following configuration:

```yaml
repos: # the repositories belonging to this team
  - go-utils
  - keptn

approvers: # list of users who are approvers for this group and its repos

maintainers: # list of users who are maintainers for this group and its repos
```

Our merger will than take all this information to generate the configuration, and apply it via GitHub Action to the defined organizations.

### References

- https://github.com/keptn/community/issues/174
- https://github.com/kubernetes/org

### Sponsors

- @thisthat 
- @mowies 
- @thschue

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".
